pkg = llvm
ver = 5.0.1

url_llvm        = http://releases.llvm.org/$ver/llvm-$ver.src.tar.xz
url_clang       = http://releases.llvm.org/$ver/cfe-$ver.src.tar.xz
url_lld       = http://releases.llvm.org/$ver/lld-$ver.src.tar.xz

sha256sum_llvm = 5fa7489fc0225b11821cab0362f5813a05f2bcf2533e8a4ea9c9c860168807b0
sha256sum_clang = 135f6c9b0cd2da1aff2250e065946258eb699777888df39ca5a5b4fe5e23d0ff
sha256sum_lld = d5b36c0005824f07ab093616bdff247f3da817cae2c51371e1d1473af717d895

<../config.mk

srcdir  = `{pwd}
destdir = `{printf '%s/%s/' "$STAGE" "$pkg-$ver"}

archive_llvm        = `{basename $url_llvm 2>/dev/null || echo /dev/null}
archive_clang       = `{basename $url_clang 2>/dev/null || echo /dev/null}
archive_lld       = `{basename $url_lld 2>/dev/null || echo /dev/null}
tarball             = ${REPO}/$pkg@$ver.tgz

# create a pack from an chroot install (see the "install" target)
$tarball:Q:
	mk fetch patch build install cleanup
	cd $destdir
	mkdir -p $(dirname $tarball)
	find . -printf '%P\0' | LC_ALL=C sort -z | \
	GZIP=-9n ${TAR} --null --no-recursion --files-from=- --owner=root --group=root --numeric-owner \
	--mode=go=rX,u+rw,a-s -czf $tarball
	printf '\n\t%s\n\n' "$tarball"

# recipe trying to follow the most common pattern in software
# building
# If it doesn't work, simply override it on a per pack basis
build:V: fetch patch
	mkdir -p $WORK/$pkg-$ver/build
	cd $WORK/$pkg-$ver/build
	cmake \
		-DCMAKE_BUILD_TYPE=Release \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_C_COMPILER=clang \
		-DCMAKE_CXX_COMPILER=clang++ \
		-DCMAKE_SKIP_RPATH=ON \
		-DLLVM_INCLUDE_TESTS=OFF \
		-DLLVM_INCLUDE_EXAMPLES=OFF \
		-DLLVM_INCLUDE_DOCS=OFF \
		-DLLVM_TOOL_LLD_BUILD=ON \
		-DLLVM_ENABLE_ASSERTIONS=ON \
		-DLLVM_ENABLE_LLD=OFF \
		-DLLVM_ENABLE_FFI=ON \
		-DLLVM_ENABLE_LIBCXX=ON \
		-DLLVM_ENABLE_PIC=ON \
		-DLLVM_ENABLE_RTTI=ON \
		-DLLVM_ENABLE_SPHINX=OFF \
		-DLLVM_ENABLE_TERMINFO=OFF \
		-DLLVM_ENABLE_ZLIB=ON \
		-DLLVM_DEFAULT_TARGET_TRIPLE="x86_64-pc-linux-musl" \
		-DGCC_INSTALL_PREFIX="/usr" \
		-DLLVM_BUILD_LLVM_DYLIB=ON \
		-DLLVM_LINK_LLVM_DYLIB=ON \
		-DCLANG_DEFAULT_CXX_STDLIB=libc++ \
		-DCLANG_DEFAULT_RTLIB=compiler-rt \
		-DCLANG_HAVE_LIBXML=OFF \
		..
	make -j${NPROC}

# install the pack to a .rootfs directory
# this is where the "pack" target will chdir to create the pack
install:QV: build
	mkdir -p $destdir
	cd $WORK/$pkg-$ver/build
	make -j${NPROC} DESTDIR=$destdir install

cleanup:V: install
	cd $destdir
	test -n "$CLEANUP" && rm -r $CLEANUP
	find . -name '*.la'   | xargs -r rm

# patch your software using everything in ./patches
patch:QV: fetch
	if [ -d "$srcdir/patches" ]; then
		cd $WORK/$pkg-$ver
		cat $srcdir/patches/*.diff | patch -Np1
	fi

# fetch the source
fetch:QV: fetch-git fetch-archive

# if $git is set, clone the repo, and checkout $ver
fetch-git:QV:
	if [ -n "$git" ]; then
		mkdir -p $WORK
		cd $WORK
		test -d $pkg-$ver || git clone -q $git $pkg-$ver
		cd $pkg-$ver
		git reset -q --hard
		git checkout -q $ver
	fi

# if $url is set, download/extract the archive, and move its
# content to a directory named $pkg-$ver
fetch-archive:QV: $WORK/$archive_llvm $WORK/$archive_clang $WORK/$archive_lld
	cd $WORK
	rm -rf $pkg-$ver
	${TAR} -J -xvf $archive_llvm
	${TAR} -J -xvf $archive_clang
	${TAR} -J -xvf $archive_lld
	mv cfe-$ver.src llvm-$ver.src/tools/clang
	mv lld-$ver.src llvm-$ver.src/tools/lld
	mv llvm-$ver.src "$pkg-$ver"

$WORK/$archive_llvm:Q:
	mkdir -p $WORK
	cd $WORK
	curl -k -L# $url_llvm > $archive_llvm
	printf "%s  %s\n" "$sha256sum_llvm" "$archive_llvm" | sha256sum -c

$WORK/$archive_clang:Q:
	mkdir -p $WORK
	cd $WORK
	curl -k -L# $url_clang > $archive_clang
	printf "%s  %s\n" "$sha256sum_clang" "$archive_clang" | sha256sum -c

$WORK/$archive_lld:Q:
	mkdir -p $WORK
	cd $WORK
	curl -k -L# $url_lld > $archive_lld
	printf "%s  %s\n" "$sha256sum_lld" "$archive_lld" | sha256sum -c

# delete everything but the pack
clean:V:
	rm -rf $WORK
	rm -rf $destdir

# remove the pack
distclean:V: clean
	rm -f $tarball
