pkg = acl
ver = 2.2.52
url = https://download.savannah.nongnu.org/releases/acl/acl-$ver.src.tar.gz
sha256sum = 179074bb0580c06c4b4137be4c5a92a701583277967acdb5546043c7874e0d23

<../default.mk


install:QV: build
	mkdir -p $destdir
	cd $WORK/$pkg-$ver
	make -j${NPROC} DESTDIR=$destdir install install-lib install-dev

