pkg = s6-linux-utils
ver = 2.4.0.2
url = http://skarnet.org/software/s6-linux-utils/s6-linux-utils-${ver}.tar.gz
sha256sum = 37e2ad9ae370af39d1a2ae4bbf26a778539e6fb4c09d47a276de3b7e66cd8508

<../default.mk
