pkg = arm-linux-musleabi-linux-headers
<../linux-headers/shared

<../default.mk

build:QV: fetch patch
	cd $WORK/$pkg-$ver
	make mrproper

install:QV: build
	mkdir -p $destdir/usr
	cd $WORK/$pkg-$ver
	make CC=arm-linux-musleabi-gcc ARCH=arm INSTALL_HDR_PATH=$destdir/usr/arm-linux-musleabi headers_install

