pkg = musl-fts
ver = 1.2.7
url = https://github.com/pullmoll/musl-fts/archive/v$ver.tar.gz

sha256sum = 49ae567a96dbab22823d045ffebe0d6b14b9b799925e9ca9274d47d26ff482a6

<../default.mk

CONFIGURE = --prefix=/usr

build:V: fetch patch
	cd $WORK/$pkg-$ver
	./bootstrap.sh
	test -f configure && ./configure $CONFIGURE
	make -j${NPROC}
