pkg = arm-linux-musleabi-musl
ver = 1.1.18
url = https://www.musl-libc.org/releases/musl-$ver.tar.gz

sha256sum = d017ee5d01aec0c522a1330fdff06b1e428cb409e1db819cc4935d5da4a5a118

<../default.mk

CONFIGURE = --target=arm-linux-musleabi \
  --host=x86_64-pc-linux-musl \
  --prefix=/usr

