pkg = bzip2
ver = 1.0.6
url = http://bzip.org/$ver/$pkg-$ver.tar.gz
sha256sum = a2848f34fcd5d6cf47def00461fcb528a0484d8edef8208d6d2e2909dc61d9cd

<../default.mk

BIGFILES = -D_FILE_OFFSET_BITS=64
CFLAGS = $CFLAGS -Wall -Winline -O2 -g $BIGFILES

