pkg = s6-overlay
ver = 1.21.2.2
url = https://github.com/just-containers/s6-overlay/archive/v${ver}.tar.gz

sha256sum = f55f7b24448719d530dfcc54352f457ed7a4132973caf3bd711be44c9eb5a7e2

<../default.mk

build:V: fetch patch
	true

# install the pack to a .rootfs directory
# this is where the "pack" target will chdir to create the pack
install:QV: build
	mkdir -p $destdir
	cd $WORK/$pkg-$ver
	cp -r builder/overlay-rootfs/* $destdir/

