pkg = i486-pc-linux-musl-musl
ver = 1.1.18
url = https://www.musl-libc.org/releases/musl-$ver.tar.gz

sha256sum = d017ee5d01aec0c522a1330fdff06b1e428cb409e1db819cc4935d5da4a5a118

<../default.mk

CONFIGURE = --target=i486-pc-linux-musl \
  --build=x86_64-pc-linux-musl \
  --prefix=/usr

build:V: fetch patch
	cd $WORK/$pkg-$ver
	test -f configure && CC=i486-pc-linux-musl-gcc CROSS_COMPILE=i486-pc-linux-musl- ./configure $CONFIGURE
	make -j${NPROC}

