pkg = i486-pc-linux-musl-linux-headers
<../linux-headers/shared
<../default.mk

build:QV: fetch patch
	cd $WORK/$pkg-$ver
	make mrproper

install:QV: build
	mkdir -p $destdir/usr
	cd $WORK/$pkg-$ver
	make CC=i486-pc-linux-musl-gcc ARCH=x86 INSTALL_HDR_PATH=$destdir/usr/i486-pc-linux-musl headers_install

