pkg = util-linux
ver = 2.31.1
url = https://www.kernel.org/pub/linux/utils/util-linux/v2.31/util-linux-$ver.tar.xz
sha256sum = 1a51b16fa9cd51d26ef9ab52d2f1de12403b810fc8252bf7d478df91b3cddf11

<../default.mk
