#!/bin/sh

target=$(basename "${0%-clang++-libc++}")
arch=$(echo "${target}" | cut -f1 -d'-')
darwin=$(echo "${target}" | cut -f3 -d'-')

exec /usr/bin/clang++ \
  -target "${target}" \
  -mlinker-version=274.2 \
  -isystem /usr/lib/clang/5.0.1/include \
  -isysroot /usr/${target} \
  -stdlib=libc++ \
  -nostdinc++ \
  -Qunused-arguments \
  -cxx-isystem /usr/${target}/usr/include/c++/v1 \
  -mmacosx-version-min=10.9.0 \
  -arch ${arch} "$@"
