pkg = tar
ver = 1.30
url =  https://ftp.gnu.org/gnu/tar/tar-$ver.tar.xz
sha256sum = f1bf92dbb1e1ab27911a861ea8dde8208ee774866c46c0bb6ead41f4d1f4d2d3

<../default.mk

build:V: fetch patch
	cd $WORK/$pkg-$ver
	test -f configure && FORCE_UNSAFE_CONFIGURE=1 ./configure $CONFIGURE
	make -j${NPROC}

