pkg = linux-headers
<shared
<../default.mk

build:QV: fetch patch
	cd $WORK/$pkg-$ver
	make mrproper

install:QV: build
	mkdir -p $destdir/usr
	cd $WORK/$pkg-$ver
	make INSTALL_HDR_PATH=$destdir/usr headers_install

