pkg = libisl
ver = 0.18
url = http://isl.gforge.inria.fr/isl-$ver.tar.xz

sha256sum = 0f35051cc030b87c673ac1f187de40e386a1482a0cfdf2c552dd6031b307ddc4

<../default.mk

build:QV: fetch patch
	cd $WORK/$pkg-$ver
	test -f configure && CFLAGS="$CFLAGS" LDFLAGS="$LDFLAGS" ./configure --prefix=/usr --enable-static --disable-shared --with-pic
	make -j${NPROC}
