pkg = curl
ver = 7.57.0
url = https://curl.haxx.se/download/curl-$ver.tar.xz
sha256sum = f5f6fd3c72b7b8389969f4fb671ed8532fa9b5bb7a5cae7ca89bc1cea45c7878

<../default.mk

CONFIGURE = $CONFIGURE --with-ca-bundle=/etc/ca-certificates/cacert.pem
