pkg = dash
ver = 0.5.9.1
url = https://git.kernel.org/pub/scm/utils/dash/dash.git/snapshot/dash-$ver.tar.gz
sha256sum = 3f747013a20a3a9d2932be1a6dd1b002ca5649849b649be0af8a8da80bd8a918

<../default.mk

build:V: fetch patch
	cd $WORK/$pkg-$ver
	./autogen.sh
	test -f configure && ./configure $CONFIGURE
	make -j${NPROC}

install:QV: build
	mkdir -p $destdir
	cd $WORK/$pkg-$ver
	make -j${NPROC} DESTDIR=$destdir install
	ln -s dash $destdir/usr/bin/sh

