pkg = ca-certificates
ver = 20170920
url = https://curl.haxx.se/ca/cacert-2017-09-20.pem
sha256sum = 435ac8e816f5c10eaaf228d618445811c16a5e842e461cb087642b6265a36856

<../default.mk

install:QV: build
	mkdir -p $destdir/etc/ca-certificates
	cp -a $SOURCES/$archive $destdir/etc/ca-certificates/cacert.pem

build:V: fetch patch
	true

fetch-archive:QV: $WORK/$archive
	true

$WORK/$archive:Q: $SOURCES/$archive
	true
